package com.wmcourse.warehouseapp.article;

public class FirstSearchTextGenerator implements SearchTextGenerator{
    @Override
    public void generateSearchText() {
        System.out.println("Text generated by FirstSearchTextGenerator.");
    }
}
