package com.wmcourse.warehouseapp.article;

public class SecondSearchTextGenerator implements SearchTextGenerator{
    @Override
    public void generateSearchText() {
        System.out.println("Text generated by SecondSearchTextGenerator.");
    }
}
