package com.wmcourse.warehouseapp.article;

public class ThirdSearchTextGenerator implements SearchTextGenerator{
    @Override
    public void generateSearchText() {
        System.out.println("Text generated by ThirdSearchTextGenerator.");
    }
}
